10 nets, 150 hiddens per net, 10 epochs per net, 200000 datapoints, 0.45 acc
sdossassgat.osm''u.thws-1scdsdsioafaawwttss'stttoscausjofbuos-ts',gwssomohom1cs-aidtsuiobpsti,sstgb.ftswdsajsucv,w,ssc,s.(ftshfpwwtddtwbsbs'sbssfgcjsfottet,rmt..st3hcpwbf`ai.afs1s.tg.fo-,a,sstsfcscdst
===========
3 nets, 200 hiddens per net, 5 epochs per net, 200000 datapoints, 0.35 acc, different attitude towards the time series...
 eud nod tiwhoe   c'mksoi  nfa tnwyiu nnc.iu tlwyyi   l,sy s7feek ertsy e`g oebnrilsolswr aecdfk fhos mih nitna dtbyoagnlei tn,ee rxco-dnsoesn aid ta'hr'o  xtaeet rhciskf r..d   rfhiotn oefdci .nm tiyan te. r ietnr ietnseahxntteh daoetnr qe,a  sif eogmt.si  nptnwa n ucheai fnn ooh ne. f hfciehn yif notenta   t(,hi  r..   frt ehcdil nxai' d'f srasol wyr aemcnehd eea d weti  nfca lgmlu tntessr cemk bet ro,an ten wxtiatntr oec'   h'. ? t ahptih tabet  o`hr eeg mhle ef6ru  ria sng iehr ce,ic tewyri stt ohn ea r tap rrii lntyoy w iigsv oipnni  th, r te.iv regsr telu  radniasnctihrtoaecv he' 'tenidgteia dnoect ao.tn oe` r mahwt eht ee, t baelnse sni tnnitnv io`d oeltyy i cfolt ihssei nr.a. m tewhti  xtsb tudi  pna tta   ba'osst eod bee sa'br ietnais ooh sew tafokor aeadft eos mt.ei   r.,   .`b nrt.n   ffaaisn titeospbea nnag uasv uednd oebn li,sn tgaehtr hr.a  xlgio nnbyeb   pbia dtbi ltmoa d we, r tot  -.is stasin tit lhae vwaitna g tr$hi  t1n. t austr iet  r,(u  r'voseo  res 't,s   .fs eva odmn itcurhsa tncrea  cna dnhwe ex.si  ttte tgg ohvl iednnea  rl, a frioa l waw2githsi  nf. o nffeo dnra tsooe ndha i mntysy ye,-- eor nas0c  l.,o  rw,od mefesdrsaotlv ret eomnci ht. h le. n a-d ootrseot  h.,  rtcomyya   wit lpgoewp ae,dy ext iagruti  reissvhoe pftroa dnd oiat nh. 5 t-g irwtaaenr oesr eep ran wcaeiskf mot   fwgiaenb cniteo  fnco hfa bs-a p arrneas ctthi tlosd toe rr,si  nwci tnwha incwaosps oe'  fa'l'si'tn aowl oa`f oolbta  ri, n wewcyia d me. n eosn otbnhyii t'd .it lhto  rfnoa  r2c0 itme a pn.a  rit  otj hii lnwo   lhse pna d cet rhieirvfeee nrceaodgl alrneut  oagnma osd o tndho kncyaesd paa p tatu' ruptc hh.ae speh  otb oaadyn aohnnea nrtei  lpjee nrha snw iobsbe axhr ai,ld lapamlniencvoeei   piisnd oah sed setsr hus lod siwtoaougnt eo, u tnssn ea' m .iw te.ht oitnse tn. s ai:spyue rlb irgmuheyin vc,ei nnwyiy fct lh.si tvmoe sfmi  v`lisla onfmt eoasfcio df'nesgso tngye  r.my aamdye   f,t  onrtemen aidn u'h sea rnta  bwma i snuasri   rec nitngoth sec ral det lo, m s
 =============
 3 nets, 200 hiddens per net, 3 epochs per net, 200000 datapoints, 0.32 acc, possibly final attitude towards time series
   tsse  ,e  ftoe nceonu gcoor ahtt  iac h,obmecrhst  ctoedn  esxt  ,d  ca`l dcoenst  o,m atmhiannd iwnl yaensiltd  btihgl esn  efntom osf own  aantt esntceo rhat equpts eest uinn dnri.l e,n  ,i tgsr tiatg etnh tihn  .a d,i u,n t,h inlnt 'f-evfiinnttn aunl n,n ggilalei ng atn osf ifn tshei dhautl rhclle gbern  -fn ihne dfoefn  icnp ytihnnoss  ,h ewfhoi ngei nggwr otn etrs  walme  'fw eyn  p,a  kt alsp oan  emre sceande gnhiegn  sa l,o rpolnre-p e,n (genr epthiisg  a.n tghee  sh .n ehrs  sltritctho umtonn egnhiinn sgearn  irn etgs  ,f  sreedn  'a5o ffoennsg  npientt amns taamnkn c.h dteyn a.r  wmi.r ag eaxlg eosp laimbt hoer ne-v  oinggth  spult iwn o-f .g  n'dt  d.a ttiaagdp ygee rcaiydy  b,l dgarn.  g11a`t  nt i,n e,r oc jd2wye8 thhei 'n  ,p yt  ,'  ,f  .f ienctt  ahres  gg1os  cfolr ecf.u mferrfocniigt st-anm ow  c5u tlaendt  baym aa di)sat ion dtfhteh-e loiwnt sass  ,o  ,r  tfhoecnt isn sisr  sass  .o terx t,h  w,o  ht'atgo sgiitlh etr t.o  g`-s earts  `a  aot thh  breinntatc ien ao tphee  nenn antd 'b3  g) alns a.t eacrpel laisnt'  ,.  b,u c.e d,o f'oesrtoavnionnyes tfhe  ubteidn a,  lfdeer  'pn efarimnatl obf  ko  strho wmaitk   atf ruaknd e.r y,o )gerrt hhilclhiitnht yo l,a mpoaudc ipntta  s'  c.o vweods tthhe vteingi nhneeavfe rtei r.o mgalny  fbwri gahn  manddr  sise nfeo teoe  boatr f,i ngsiesna lluoinneawdg u3nr ywri cohnueln e'i0d  m.l bluatntu f,r ygoonn  .a l,rvye rbriodr opne.s  balt  l4ni gc t.h yr e.s  ah lnos  lhlisptiidgtwa tfo l.e saonr imv e.r ah d,asy  ,o  bpoosp eanr' sitnhiang rfisst afn ccaigneingn sset-ohn  ewreegs  cshte rsltlt.  bpie d,r epafnwniovp riecse mbornliltl ehr  fnosr sfi.o 'f0  g.o tceo meartn awne smeersusu n.a s.2 kotn ocreess eh mcoonfdi tgoernakr  tiicnt  bf omf iwnreadmd  tsw syepns tbhe rpalrg ecrr etnr o.  2fwoasn  feoenn'  arnt h'es'  .,  ,)  cfaotc ii'n  1a dbaosn  ,,  ,,  c,i vneer vse glaitdes  mhoirr esn ehx l,auttso ltl .$ eintl  thoa nhotgeayg ohn  .h tuhr  hirnn gboaacd  1t`  b,u roem  ta  fa l,r e,r  .,  .f raem r

